---
- name: Analyze alerts from collected logs
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run alert analysis script
      command: ~/Desktop/ansible_playbooks/automated_Incident_Response/alert_analysis.sh # This is the path of the bash script used to investigate alerts
      register: alert_analysis_output
      ignore_errors: true

    - name: Display alert analysis results
      debug:
        msg: "{{ alert_analysis_output.stdout }}"

    - name: Setting fact if issue found
      set_fact:
        issue_found: true
      when: alert_analysis_output.rc != 0
